intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import intf_libs =+ libzycore%lib{zycore}

# Public headers.
#
pub = [dir_path] ../include/Zydis/
include $pub
pub_hdrs = $($pub/ pub_hdrs)

# Private headers
#
define inc: file
inc{*}: extension = inc
priv = {h c inc}{**}

lib{zydis}: libul{zydis}: $pub/{$pub_hdrs} $priv $impl_libs $intf_libs

# Zydis depends on Zycore, which only define ZYAN_DLLEXPORT as
# __declspec(dllexport) when ZYAN_MSVC is defined. However, in some cases we may
# be using a different compiler such as Clang on Windows. Here, symbol export
# will fail because ZYAN_DLLEXPORT remains undefined or expands to nothing.
#
# To work around this, we auto export symbols when compiling with Clang on
# Windows
#
libs{zydis}: def{zydis}: include = ($c.target.system == 'win32-msvc')
             def{zydis}: libul{zydis}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

if ($c.id == 'clang')
  cxx.loptions += -Wl,--export-all-symbols

obja{*}: c.poptions += -DZYDIS_STATIC_BUILD
objs{*}: c.poptions += -DZYDIS_SHOULD_EXPORT

# Export options.
#
lib{zydis}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

liba{zydis}: c.export.poptions += -DZYDIS_STATIC_BUILD
libs{zydis}: c.export.poptions += -DZYDIS_SHOULD_EXPORT

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{zydis}: bin.lib.version = "-$version.project_id"
else
  lib{zydis}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
